name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      scheme:
        description: '选择打包架构 (rootless, roothide, rootful)'
        required: true
        default: 'rootless'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: kabiroberai/install-theos-action@v1

      - name: Build Package
        run: |
          # 使用 Makefile 里的 SCHEME 逻辑
          make package SCHEME=${{ github.event.inputs.scheme || 'rootless' }} FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tweak-Deb
          path: packages/*.deb
