      - name: Setup Theos
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          rm -rf ~/theos
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      # 插入下面这个步骤来修复 ldid 缺失问题
      - name: Install ldid
        run: |
          brew install ldid
          # 确保 Theos 能找到它（有时候 brew 安装路径需要手动链接或确认）
          which ldid
